%\VignetteKeywords{Database}
%\VignetteDepends{prostateCancerGrasso}
%\VignettePackage{prostateCancerGrasso}
%\VignetteIndexEntry{prostateCancerGrasso}

\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}


In this document, I describe how the GEO data entry for the Varambally data was processed and saved into an object for analysis in Bioconductor. First of all load the relevant libraries for grabbing and manipulaing the data

<<>>=
library(GEOquery)
library(dplyr)
library(tidyr)

@


Now use the `getGEO` function with the correct ID

<<>>=
geoData <- getGEO("GSE35988")
geoData
@


The phenoData contains lots of metadata from GEO that probably won't be useful for our analysis

<<>>=
pd <- rbind(pData(geoData[[1]]),pData(geoData[[2]]))

groups = NULL
groups[grep('benign', pd$characteristics_ch2, perl=TRUE)] = "Benign"
groups[grep('localized', pd$characteristics_ch2, perl=TRUE)] = "HormomeDependant"
groups[grep('metastatic', pd$characteristics_ch2, perl=TRUE)] = "CastrateResistant"

pd <- data.frame(geo_accession=pd$geo_accession, Group=groups)

fd <- fData(geoData[[1]])[,c("ID","GENE","GENE_SYMBOL")]

exp <- cbind(exprs(geoData[[1]]), exprs(geoData[[2]]))

geoData <- geoData[[1]]
exprs(geoData) <- exp
pData(geoData) <- pd
fData(geoData) <- fd

grasso <- geoData
save(grasso, file="data/grasso.rda",compress="xz")
@






\end{document}